//
// <DISCLAIMER BEGIN>
//
// Copyright (c) 1997-2000 Solipsys Corporation. All Rights Reserved.
//
// This software is the confidential and proprietary information of
// Solipsys Corporation. (Solipsys Proprietary).  You shall not disclose
// such Confidential Information and shall use it only in accordance with
// the terms of the license agreement you entered into with Solipsys.  
//
// SOLIPSYS MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY
// OF THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
// TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE, OR NON-INFRINGEMENT. SOLIPSYS SHALL NOT BE LIABLE FOR ANY
// DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING, MODIFYING OR
// DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.  
//
// *DO*NOT*EDIT                    ***WARNING***               *DO*NOT*EDIT*
// *DO*NOT*EDIT  This file is automatically generated by the   *DO*NOT*EDIT*
// *DO*NOT*EDIT  cajun.pl meta language parser. Modifications  *DO*NOT*EDIT*
// *DO*NOT*EDIT  made inside of the CAJUN CODE blocks will be  *DO*NOT*EDIT*
// *DO*NOT*EDIT  lost.                                         *DO*NOT*EDIT*
// *DO*NOT*EDIT                    ***WARNING***               *DO*NOT*EDIT*
//
// <DISCLAIMER END>
//

package examples;

import solinet.Jstring;
import solinet.Time;
import java.io.DataOutputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.io.PrintStream;

public class SolidInfo
{
  int inetAddress;
  int netPortUDP;
  int netPortTCP;
  int processId;
  Time timeStamp;
  Jstring hostname;

  public SolidInfo( )
  {
    setInetAddress(0);
    setNetPortUDP(0);
    setNetPortTCP(0);
    setProcessId(0);
    timeStamp = new Time();
    hostname = new Jstring();
  }


  public int lengthObj()
  {
    return(
     4 + // inetAddress (int)
     4 + // netPortUDP (int)
     4 + // netPortTCP (int)
     4 + // processId (int)
     timeStamp.lengthObj() +
     hostname.lengthObj() +
     0
    );
  }

  public void setInetAddress( int v ) { inetAddress = v; }
  public int getInetAddress() { return( inetAddress ); }

  public void setNetPortUDP( int v ) { netPortUDP = v; }
  public int getNetPortUDP() { return( netPortUDP ); }

  public void setNetPortTCP( int v ) { netPortTCP = v; }
  public int getNetPortTCP() { return( netPortTCP ); }

  public void setProcessId( int v ) { processId = v; }
  public int getProcessId() { return( processId ); }

  public void setTimeStamp( Time v ) { timeStamp = v; }
  public Time getTimeStamp() { return( timeStamp ); }

  public void setHostname( Jstring v ) { hostname = v; }
  public Jstring getHostname() { return( hostname ); }

  public void serialize( DataOutputStream out )
  {
   try {
      out.writeInt( inetAddress );
      out.writeInt( netPortUDP );
      out.writeInt( netPortTCP );
      out.writeInt( processId );
      timeStamp.serialize( out );
      hostname.serialize( out );
    }
   catch( Exception e ) { e.printStackTrace( ); }
  }

  public void deserialize( DataInputStream in )
  {
   try {
      inetAddress = in.readInt( );
      netPortUDP = in.readInt( );
      netPortTCP = in.readInt( );
      processId = in.readInt( );
      timeStamp.deserialize( in );
      hostname.deserialize( in );
    }
   catch( Exception e ) { e.printStackTrace( ); }
  }

  public void println( PrintStream ps )
  {
    ps.println( "-- SolidInfo:: ----------------------------------------" );
    ps.println( "  InetAddress: " + inetAddress );
    ps.println( "  NetPortUDP: " + netPortUDP );
    ps.println( "  NetPortTCP: " + netPortTCP );
    ps.println( "  ProcessId: " + processId );
    timeStamp.println( ps );
    hostname.println( ps );
  }

}
